### ISSUE TITLE
Can not load the pre-trained models.

### ISSUE THREAD

**Issue by ghost** [TheLegendAli/DeepLab-Context#31]
Hi Ali. Thanks for this program. I have one issue - can not load model:
Downloading init caffemodel from http://ccvl.stat.ucla.edu/ccvl/init_models/vgg16_20M.caffemodel
Traceback (most recent call last):
  File "run.py", line 67, in <module>
    run(RUN_TRAIN, RUN_TEST, RUN_TRAIN2, RUN_TEST2, RUN_SAVE)
  File "run.py", line 55, in run
    if RUN_TRAIN : trainer()
  File "/home/lumius/Dropbox/DeepLab-Context/python/my_script/trainer.py", line 52, in trainer
    model = train_prototxt_maker(train, init, solver, train_set)
  File "/home/lumius/Dropbox/DeepLab-Context/python/my_script/trainer.py", line 32, in train_prototxt_maker
    if not os.path.isfile(model): model=model_finder(os.environ['EXP']+ '/model/' + os.environ['NET_ID'])
  File "/home/lumius/Dropbox/DeepLab-Context/python/my_script/tools.py", line 16, in model_finder
    filename = wget.download(url)
  File "/usr/local/lib/python2.7/dist-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 673, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 642, in http_error_302
    headers, data)
  File "/usr/lib/python2.7/urllib.py", line 669, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
then run run.py

**Comment by entanglelove** [comment]
open the file at  /home/lumius/Dropbox/DeepLab-Context/python/my_script/tools.py
change the url 
** http://ccvl.stat.ucla.edu/ccvl/init_models/vgg16_20M.caffemodel**
into
http://www.cs.jhu.edu/~alanlab/ccvl/init_models/vgg16_20M.caffemodel

**Comment by ghost** [comment]
Thanks!
